#!/usr/bin/env python3
"""
create_pr.py
Creates a new branch, commits the fix, pushes it, and opens a GitHub PR.
Uses the GitHub REST API directly (no external dependencies beyond requests).
"""

import argparse
import json
import os
import subprocess
import sys
import time

import requests


GITHUB_API = "https://api.github.com"


def run(cmd: list[str], check=True) -> subprocess.CompletedProcess:
    """Run a shell command and return the result."""
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"[ERROR] Command failed: {' '.join(cmd)}")
        print(result.stderr)
        sys.exit(1)
    return result


def load_fix(fix_path: str) -> dict:
    with open(fix_path) as f:
        return json.load(f)


def create_branch_and_commit(fix_data: dict, base_branch: str) -> str:
    """Create a timestamped fix branch, commit the changed file, push."""
    timestamp = int(time.time())
    fix_branch = f"ai-fix/{base_branch}-{timestamp}"

    run(["git", "checkout", "-b", fix_branch])

    source_path = fix_data.get("source_path", "")
    if source_path:
        run(["git", "add", source_path])

    commit_msg = (
        f"fix(ai-agent): {fix_data.get('issue_summary', 'Auto-fix from AI Dev Agent')}\n\n"
        f"Root cause: {fix_data.get('root_cause', 'N/A')}\n"
        f"Fix applied: {fix_data.get('fix_description', 'N/A')}\n\n"
        "This commit was generated automatically by the AI Dev Agent."
    )
    run(["git", "commit", "-m", commit_msg])
    run(["git", "push", "origin", fix_branch])

    print(f"[INFO] Pushed branch: {fix_branch}")
    return fix_branch


def create_github_pr(repo: str, fix_branch: str, base_branch: str, fix_data: dict) -> str:
    """Open a pull request via the GitHub API and return its URL."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("[ERROR] GITHUB_TOKEN environment variable not set.")
        sys.exit(1)

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    title = f"[AI Fix] {fix_data.get('issue_summary', 'Automated fix from AI Dev Agent')}"
    body = f"""## 🤖 AI Dev Agent — Automated Fix

This PR was created automatically after a CI/CD pipeline failure was detected on `{base_branch}`.

---

### 🔍 Issue Summary
{fix_data.get('issue_summary', 'N/A')}

### 🧠 Root Cause
{fix_data.get('root_cause', 'N/A')}

### 🔧 Fix Applied
{fix_data.get('fix_description', 'N/A')}

---

> **Note:** Review the changes carefully before merging.
> Generated by [AI Dev Agent](https://github.com/{repo}/actions).
"""

    payload = {
        "title": title,
        "body": body,
        "head": fix_branch,
        "base": base_branch,
        "draft": False,
    }

    url = f"{GITHUB_API}/repos/{repo}/pulls"
    resp = requests.post(url, headers=headers, json=payload, timeout=30)

    if resp.status_code == 201:
        pr_url = resp.json().get("html_url")
        print(f"[INFO] PR created: {pr_url}")
        return pr_url
    else:
        print(f"[ERROR] GitHub API returned {resp.status_code}: {resp.text}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Create a GitHub PR with the AI-generated fix")
    parser.add_argument("--fix", required=True, help="Path to Gemini fix JSON")
    parser.add_argument("--base", required=True, help="Base branch to target (original PR branch)")
    parser.add_argument("--repo", required=True, help="GitHub repo in owner/repo format")
    args = parser.parse_args()

    fix_data = load_fix(args.fix)

    fix_branch = create_branch_and_commit(fix_data, args.base)
    pr_url = create_github_pr(args.repo, fix_branch, args.base, fix_data)

    print(f"\n✅ AI fix PR ready for review: {pr_url}")


if __name__ == "__main__":
    main()
